//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment_Questions
    {
        public int QuestionID { get; set; }
        public string QuestionDisplayName { get; set; }
        public string QuestionDisplayGuidance { get; set; }
        public string InternalName { get; set; }
        public string InternalCode { get; set; }
        public Nullable<byte> Archive { get; set; }
        public Nullable<int> QuestionSetID { get; set; }
    
        public virtual Assessment_QuestionSets Assessment_QuestionSets { get; set; }
    }
}
