//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment_QuestionSets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment_QuestionSets()
        {
            this.Assessment_Questions = new HashSet<Assessment_Questions>();
        }
    
        public int QuestionSetID { get; set; }
        public string QuestionSetDisplayName { get; set; }
        public string QuestionSetInternalName { get; set; }
        public Nullable<byte> Archived { get; set; }
        public Nullable<int> Order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assessment_Questions> Assessment_Questions { get; set; }
    }
}
